version: '3'
services:

  #Nginx Service
  webserver:
    image: wactrum/avem-player-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: avem-player-frontend
    volumes:
      - ./deployment/nginx/$APP_TYPE/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/cert:/var/cert
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
