version: '3'
services:

  #Nginx Service
  webserver:
    image: ${DOCKER_USER}/${IMAGE_NAME}:${TAG}
    container_name: avem-player-frontend
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/var/cert
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
